### ISSUE TITLE
Happens for some inputs

### ISSUE THREAD

**Issue by M4rotte** [M4rotte/ShorewallLogAnalyzer#1]
```
$ ./Whois.py 
Traceback (most recent call last):
  File "./Whois.py", line 43, in getResult
    value = block[key]+"\n"+kv[1].strip()
KeyError: '                hack attacks, illegal activity,'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./Whois.py", line 69, in <module>
    pprint(whois.getResult())
  File "./Whois.py", line 49, in getResult
    value = kv[1]
IndexError: list index out of range
```

**Comment by M4rotte** [comment]
Whois.py no more part of this project
