### ISSUE TITLE
At least the database is closed \o/

### ISSUE THREAD

**Issue by M4rotte** [M4rotte/ShorewallLogAnalyzer#3]
2016-07-08 22:43:46.087527 updatePackets: Database locked. Exiting.
Traceback (most recent call last):
  File "./ShorewallLogAnalyzer.py", line 208, in <module>
    analyzer.updatePackets()
  File "./ShorewallLogAnalyzer.py", line 136, in updatePackets
    p['ip']['MAC']))
sqlite3.ProgrammingError: Cannot operate on a closed database.
stef@medusa:~/Code/ShorewallLogAnalyzer$ ./ShorewallLogAnalyzer.py

**Comment by M4rotte** [comment]
Should be fixed
